# Generated by Django 5.1.1 on 2024-09-20 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitivinicultura", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producao",
            name="control",
        ),
        migrations.AddField(
            model_name="producao",
            name="tipo",
            field=models.CharField(default="default_tipo", max_length=255),
        ),
        migrations.AlterField(
            model_name="anoproducao",
            name="ano",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="anoproducao",
            name="quantidade",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="producao",
            name="produto",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="Comercio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produto", models.CharField(max_length=255)),
                ("tipo", models.CharField(default="default_tipo", max_length=255)),
                ("ano", models.ManyToManyField(to="vitivinicultura.anoproducao")),
            ],
        ),
        migrations.CreateModel(
            name="Exportacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pais", models.CharField(max_length=100)),
                ("valor_usd", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "ano_producao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exportacoes",
                        to="vitivinicultura.anoproducao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Importacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pais", models.CharField(max_length=100)),
                ("valor_usd", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "ano_producao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="importacoes",
                        to="vitivinicultura.anoproducao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Processamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cultivo", models.CharField(max_length=255)),
                ("tipo", models.CharField(default="default_tipo", max_length=255)),
                ("ano", models.ManyToManyField(to="vitivinicultura.anoproducao")),
            ],
        ),
    ]
