# Generated by Django 5.1.1 on 2024-09-20 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitivinicultura", "0002_remove_producao_control_producao_tipo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exportacao",
            name="ano_producao",
        ),
        migrations.RemoveField(
            model_name="importacao",
            name="ano_producao",
        ),
        migrations.RemoveField(
            model_name="processamento",
            name="ano",
        ),
        migrations.RemoveField(
            model_name="producao",
            name="ano",
        ),
        migrations.RemoveField(
            model_name="comercio",
            name="ano",
        ),
        migrations.RemoveField(
            model_name="exportacao",
            name="pais",
        ),
        migrations.RemoveField(
            model_name="exportacao",
            name="valor_usd",
        ),
        migrations.RemoveField(
            model_name="importacao",
            name="pais",
        ),
        migrations.RemoveField(
            model_name="importacao",
            name="valor_usd",
        ),
        migrations.RemoveField(
            model_name="processamento",
            name="cultivo",
        ),
        migrations.AddField(
            model_name="exportacao",
            name="produto",
            field=models.CharField(default="produto_desconhecido", max_length=100),
        ),
        migrations.AddField(
            model_name="exportacao",
            name="tipo",
            field=models.CharField(default="tipo_desconhecido", max_length=100),
        ),
        migrations.AddField(
            model_name="importacao",
            name="produto",
            field=models.CharField(default="produto_desconhecido", max_length=100),
        ),
        migrations.AddField(
            model_name="importacao",
            name="tipo",
            field=models.CharField(default="tipo_desconhecido", max_length=100),
        ),
        migrations.AddField(
            model_name="processamento",
            name="produto",
            field=models.CharField(default="produto_desconhecido", max_length=100),
        ),
        migrations.AlterField(
            model_name="comercio",
            name="produto",
            field=models.CharField(default="produto_desconhecido", max_length=100),
        ),
        migrations.AlterField(
            model_name="comercio",
            name="tipo",
            field=models.CharField(default="tipo_desconhecido", max_length=100),
        ),
        migrations.AlterField(
            model_name="processamento",
            name="tipo",
            field=models.CharField(default="tipo_desconhecido", max_length=100),
        ),
        migrations.AlterField(
            model_name="producao",
            name="produto",
            field=models.CharField(default="produto_desconhecido", max_length=100),
        ),
        migrations.AlterField(
            model_name="producao",
            name="tipo",
            field=models.CharField(default="tipo_desconhecido", max_length=100),
        ),
        migrations.CreateModel(
            name="AnoValor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField(default=1970)),
                ("valor", models.BigIntegerField(default=0)),
                (
                    "comercio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vitivinicultura.comercio",
                    ),
                ),
                (
                    "exportacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vitivinicultura.exportacao",
                    ),
                ),
                (
                    "importacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vitivinicultura.importacao",
                    ),
                ),
                (
                    "processamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vitivinicultura.processamento",
                    ),
                ),
                (
                    "producao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vitivinicultura.producao",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AnoProducao",
        ),
    ]
