# Generated by Django 5.1.1 on 2024-10-15 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vitivinicultura",
            "0005_remove_comercio_pais_remove_exportacao_pais_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="exportacao",
            name="pais",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vitivinicultura.pais",
            ),
        ),
        migrations.AddField(
            model_name="importacao",
            name="pais",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vitivinicultura.pais",
            ),
        ),
    ]
