# Generated by Django 5.1.1 on 2024-10-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitivinicultura", "0006_pais_exportacao_pais_importacao_pais"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anovalor",
            name="valor",
            field=models.FloatField(default=0.0),
        ),
    ]
