# Generated by Django 5.1.1 on 2024-10-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitivinicultura", "0007_alter_anovalor_valor"),
    ]

    operations = [
        migrations.AddField(
            model_name="anovalor",
            name="tipo_valor",
            field=models.CharField(default="quantidade", max_length=50),
        ),
    ]
