# Generated by Django 5.1.1 on 2024-10-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitivinicultura", "0009_alter_anovalor_tipo_valor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exportacao",
            name="produto",
        ),
        migrations.RemoveField(
            model_name="exportacao",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="importacao",
            name="produto",
        ),
        migrations.RemoveField(
            model_name="importacao",
            name="tipo",
        ),
        migrations.AlterField(
            model_name="exportacao",
            name="pais",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="importacao",
            name="pais",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="pais",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
