# Generated by Django 5.1.1 on 2024-10-16 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vitivinicultura",
            "0010_remove_exportacao_produto_remove_exportacao_tipo_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anovalor",
            options={
                "verbose_name": "Ano e Valor",
                "verbose_name_plural": "Anos e Valores",
            },
        ),
        migrations.AlterField(
            model_name="anovalor",
            name="ano",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="anovalor",
            name="comercio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anos_valores",
                to="vitivinicultura.comercio",
            ),
        ),
        migrations.AlterField(
            model_name="anovalor",
            name="exportacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anos_valores",
                to="vitivinicultura.exportacao",
            ),
        ),
        migrations.AlterField(
            model_name="anovalor",
            name="importacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anos_valores",
                to="vitivinicultura.importacao",
            ),
        ),
        migrations.AlterField(
            model_name="anovalor",
            name="processamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anos_valores",
                to="vitivinicultura.processamento",
            ),
        ),
        migrations.AlterField(
            model_name="anovalor",
            name="producao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anos_valores",
                to="vitivinicultura.producao",
            ),
        ),
        migrations.AlterField(
            model_name="exportacao",
            name="pais",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exportacoes",
                to="vitivinicultura.pais",
            ),
        ),
        migrations.AlterField(
            model_name="importacao",
            name="pais",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="importacoes",
                to="vitivinicultura.pais",
            ),
        ),
        migrations.AlterField(
            model_name="pais",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
