# Generated by Django 5.1.1 on 2024-10-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitivinicultura", "0011_alter_anovalor_options_alter_anovalor_ano_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportacao",
            name="produto",
            field=models.CharField(default="produto_desconhecido", max_length=100),
        ),
        migrations.AddField(
            model_name="importacao",
            name="produto",
            field=models.CharField(default="produto_desconhecido", max_length=100),
        ),
    ]
