# Generated by Django 5.1.1 on 2024-10-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitivinicultura", "0012_exportacao_produto_importacao_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportacao",
            name="tipo",
            field=models.CharField(default="tipo_desconhecido", max_length=100),
        ),
        migrations.AddField(
            model_name="importacao",
            name="tipo",
            field=models.CharField(default="tipo_desconhecido", max_length=100),
        ),
    ]
