name: Deploy

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      continue-on-error: true
      uses: azure/login@v1      
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Azure Container Registry Login
      run: |
        #az acr login --name ${{ secrets.REGISTRY_NAME }}

    - name: Build Docker image
      run: |
        cd techchallenge 
        #docker build -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:${{ github.sha }} .
        ls -lart
        docker build -t tech .


    - name: Run Trivy vulnerability scanner
      continue-on-error: true
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: 'tech'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
  

    - name: Push Docker image to ACR
      run: |
        #docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:${{ github.sha }}

    - name: Log out from Azure
      run: |
        #az logout
