name: Python Code Quality and Security Analysis

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  code-quality-and-security:
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
        options: >-
          --health-cmd="curl -f http://localhost:9000/api/system/health"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
        env:
          SONARQUBE_JDBC_URL: jdbc:postgresql://localhost/sonarqube
          SONARQUBE_JDBC_USERNAME: sonar
          SONARQUBE_JDBC_PASSWORD: sonar

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Horusec for security analysis
      run: |
        curl -fsSL https://horusec.io/bin/install.sh | bash
        horusec start -p ./ --log-level=info

    - name: Prepare SonarQube configuration
      run: |
        sonar-scanner \
          -Dsonar.projectKey=my_project_key \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=my_sonarqube_token

    - name: Run SonarQube Scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=my_project_key \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=$SONAR_TOKEN
